### ISSUE TITLE
There is currently no date management

### ISSUE THREAD

**Issue by kb-m** [pgroot/express-swagger-generator#72]
Hello,

Can you add new type 'date' ?
Swagger represents it in the following format :
```yml
date:
  type: string
  format: date
  description: Date description
```
